baseurl = "/"
languageCode = "en-us"
title = "Rivet Design System"
paginate = 10
[params]
    myVar = "Hi"
    description = "How do we design great experiences for users across UITS applications? Creating consistent front end code and documenting UX design best practices is a great place to start! "

