baseurl: "/"
languageCode: "en-us"
title: "Rivet"
paginate: 10
enableEmoji: true
params:
    tagline: "Software Design System"
    googleAnalytics: "UA-100560495-3"
    devGoogleAnalytics: "UA-100560495-4"
    githubRepo: "https://github.iu.edu/UITS/rivet-source"
    downloadLink: "https://github.iu.edu/UITS/rivet/archive/v0.3.1.zip"
    axureKit: "https://github.iu.edu/UITS/rivet/releases/download/v0.3.1/rivet-axure-0.3.1.rp"
    resourceLinks:
        -
            text: "User Experience Office"
            url: "https://uxo.iu.edu"
        -
            text: "Accessibility Evaluations"
            url: "https://a11y.iu.edu/"
        -
            text: "Rivet Software Design System"
            url: "/"
            self: true
        -
            text: "IU Framework for WCMS"
            url: "https://framework.iu.edu/"
