baseurl: "/"
languageCode: "en-us"
title: "Rivet"
paginate: 10
enableEmoji: true
params:
    tagline: "Software Design System"
    googleAnalytics: "UA-100560495-3"
    devGoogleAnalytics: "UA-100560495-4"
    githubRepo: "https://github.iu.edu/UITS/rivet-source"
    downloadLink: "https://github.iu.edu/UITS/rivet/archive/v0.2.0.zip"
    axureKit: "https://github.iu.edu/UITS/rivet-source/releases/download/v0.2.0/rivet-axure-0.2.0.rp"
    resourceLinks:
        -
            text: "User Experience Office"
            url: "https://uxo.iu.edu"
        -
            text: "Accessibility"
            url: "https://uxo.iu.edu/accessibility"
        -
            text: "Rivet Software Design System"
            url: "https://rivet.uits.iu.edu"
        -
            text: "IU Framework for WCMS"
            url: "https://framework.iu.edu"
